Layout/EndOfLine:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Lint/AssignmentInCondition:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/Next: 
  Enabled: false
#########################
### Manual Exclusions ### 
#########################

Layout/ElseAlignment:
  Exclude:
    - 'cookbooks/ey-base/attributes/snapshot_and_backup_intervals.rb'
Layout/EndAlignment:
  Exclude:
    - 'cookbooks/ey-base/attributes/snapshot_and_backup_intervals.rb'
    - 'cookbooks/ey-lib/libraries/get_pool_size.rb'
Layout/IndentationWidth:
  Exclude:
    - 'cookbooks/ey-base/attributes/snapshot_and_backup_intervals.rb'
Layout/CaseIndentation:
  Exclude:
    - 'cookbooks/ey-lib/libraries/get_pool_size.rb'
Lint/UselessAssignment:
  Exclude:
    - 'cookbooks/ey-lib/libraries/app_server_configs.rb'
    - 'cookbooks/ey-lib/libraries/get_pool_size.rb'
Chef/Correctness/MetadataMissingName:
  Exclude:
    - 'cookbooks/ey-lib/libraries/metadata.rb'
Chef/Correctness/MetadataMissingVersion:
  Exclude:
    - 'cookbooks/ey-lib/libraries/metadata.rb'
Style/Semicolon:
  Exclude:
    - 'cookbooks/ey-lib/libraries/metadata.rb'
Style/RedundantSelf:
  Exclude:
    - 'cookbooks/ey-lib/libraries/ey-engineyard.rb'
    - 'cookbooks/ey-lib/libraries/get_pool_size.rb'
Lint/NestedMethodDefinition:
  Exclude:
    - 'cookbooks/ey-lib/libraries/ey-engineyard.rb'
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'cookbooks/ey-cron/recipes/default.rb'